
import { useState } from 'react';
import { toast } from 'sonner';
import ImageUploader from '@/components/ImageUploader';
import { Card } from '@/components/ui/card';
import { cn } from '@/lib/utils';
import Navbar from '@/components/Navbar';

const Upload = () => {
  const [result, setResult] = useState<{ type: string; confidence: number } | null>(null);

  const handleUpload = async (file: File) => {
    try {
      // For now, we'll simulate the API call
      await new Promise(resolve => setTimeout(resolve, 2000));
      const isAI = Math.random() > 0.5;
      const confidence = Math.floor(Math.random() * 30) + 70; // Random number between 70-99
      const mockResult = {
        type: isAI ? "AI-Generated" : "Real",
        confidence
      };
      setResult(mockResult);
      toast.success(`Analysis complete: ${mockResult.type} (${mockResult.confidence}% confidence)`);
    } catch (error) {
      console.error('Error:', error);
      toast.error('Failed to analyze image');
    }
  };

  return (
    <div className="min-h-screen bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-900 via-purple-900 to-slate-900">
      <Navbar isAuthenticated />
      <div className="pt-32 pb-12 px-4">
        <div className="max-w-4xl mx-auto space-y-8">
          <div className="text-center space-y-4 animate-fade-up">
            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl bg-clip-text text-transparent bg-gradient-to-b from-white to-white/70">
              Analyze Your Image
            </h1>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Upload an image to instantly determine whether it was created by artificial intelligence or captured in reality.
            </p>
          </div>

          <ImageUploader onUpload={handleUpload} />

          {result && (
            <Card className="p-6 result-card bg-black/40 backdrop-blur-sm border-white/10">
              <div className="text-center space-y-4">
                <h2 className="text-2xl font-semibold text-white">Analysis Result</h2>
                <div className="flex flex-col items-center gap-2">
                  <div className="w-24 h-24 rounded-full bg-black/50 flex items-center justify-center border border-white/10">
                    <span className="text-3xl font-bold text-primary">
                      {result.confidence}%
                    </span>
                  </div>
                  <p className={cn(
                    "text-lg font-medium",
                    result.type === "Real" ? "text-green-400" : "text-orange-400"
                  )}>
                    {result.confidence}% confident this image is {result.type}
                  </p>
                  <p className="text-sm text-muted-foreground">
                    Our AI analysis suggests this is most likely {result.type === "Real" ? "a real photograph" : "generated by AI"}
                  </p>
                </div>
              </div>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
};

export default Upload;
